# Generated by Django 2.0.6 on 2018-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_employee_has_admin_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.FileField(default='media/profile-photo.jpg', upload_to='media'),
        ),
    ]
