# Generated by Django 2.0.6 on 2018-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0005_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
