# Generated by Django 2.0.6 on 2018-11-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_auto_20181110_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic0', models.FileField(upload_to='media')),
                ('pic1', models.FileField(upload_to='media')),
                ('pic2', models.FileField(upload_to='media')),
                ('pic3', models.FileField(upload_to='media')),
                ('pic4', models.FileField(upload_to='media')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.Employee')),
            ],
        ),
    ]
