# Generated by Django 2.0.6 on 2018-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0007_employeephotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic0', models.FileField(upload_to='media')),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
