# Generated by Django 2.0.6 on 2018-11-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0008_attendancelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
    ]
