# Generated by Django 2.0.6 on 2018-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='pendingalerts',
            old_name='emp_id',
            new_name='emp',
        ),
    ]
